codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

github_checks:
  annotations: true

coverage:
  precision: 2
  round: down
  range: "70..100"
  status:
    project:
      default:
        target: 90
        threshold: 2
    patch:
      default:
        target: 90
        threshold: 1

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: true

flags:
  rust-unit:
    paths:
      - src
      - benches
      - tests
    carryforward: true

ignore:
  - "target"
  - "coverage"
  - "docs/completions"
  - "docs/man"
  - "docs/book"
