min_version = "2025.9.10"

[tools]
rust = { version = "1.90.0", components = "rustfmt,clippy,llvm-tools-preview" }
"cargo:cargo-binstall" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-llvm-cov" = "latest"
"cargo:typos-cli" = "latest"
"cargo:cargo-insta" = "latest"
"cargo:cargo-deny" = "latest"
node = "lts"
"npm:markdownlint-cli2" = "latest"

[tasks.fmt]
description = "Format all source files"
run = ["cargo fmt --all"]

[tasks.lint]
description = "Clippy (pedantic), typos, markdown lint, and dependency audit"
run = [
  "cargo clippy --all-targets --all-features -- -D warnings",
  "typos",
  "markdownlint-cli2 \"**/*.md\" \"#target\" \"#coverage\" \"#dist\"",
  "cargo deny check",
]

[tasks.lint-fix]
description = "Auto-fix formatting, spelling, and markdown issues"
run = [
  "cargo fmt --all",
  "typos -w",
  "markdownlint-cli2 --fix \"**/*.md\" \"#target\" \"#coverage\" \"#dist\"",
]

[tasks.test]
description = "Run the nextest test suite"
run = ["cargo nextest run --workspace --all-targets --no-fail-fast", "cargo insta test"]
[tasks.check]
description = "Aggregate format, lint, test, and doctest runs"
depends = ["fmt", "lint", "test", "test-doc"]

[tasks.test-doc]
description = "Run Rust doctests"
run = ["cargo test --doc"]

[tasks.coverage]
description = "Generate HTML and lcov coverage reports"
run = [
  "cargo llvm-cov clean --workspace",
  "cargo llvm-cov nextest --workspace --all-targets --fail-under-lines 90 --html --output-dir coverage/html",
  "cargo llvm-cov report --summary-only",
  "cargo llvm-cov report --lcov --output-path coverage/lcov.info",
]

[tasks.bench]
description = "Run Criterion benchmarks"
run = ["cargo bench --features benchmarks --bench pipeline"]

[tasks.pkg-install]
description = "Install the CLI locally via cargo"
run = ["cargo install --path . --force"]

[tasks.generate-completions]
description = "Generate shell completions into docs/completions"
run = [
  "cargo run --bin tx -- completions bash --dir docs/completions",
  "cargo run --bin tx -- completions zsh --dir docs/completions",
  "cargo run --bin tx -- completions fish --dir docs/completions",
  "cargo run --bin tx -- completions powershell --dir docs/completions",
  "cargo run --bin tx -- completions elvish --dir docs/completions",
]

[tasks.generate-manpage]
description = "Render the CLI man page into docs/man"
run = ["cargo run --bin tx -- manpage --dir docs/man"]

[tasks.doc]
description = "Build API docs and open them in a browser"
run = ["cargo doc --no-deps --open"]

[tasks.dist-init]
description = "Initialise cargo-dist configuration"
run = ["cargo dist init"]

[tasks.dist-plan]
description = "Plan the next cargo-dist release"
run = ["cargo dist plan"]

[tasks.dist-build]
description = "Build release artefacts with cargo-dist"
run = ["cargo dist build"]

[tasks.snapshot]
description = "Run insta snapshot tests"
run = ["cargo insta test"]

[tasks.snapshot-review]
description = "Interactively review insta snapshot updates"
run = ["cargo insta review"]

[tasks.dist-doc]
description = "Explain how to configure cargo-dist"
run = ["cat docs/src/reference/releasing.md"]
