nextest-version = "0.9.95"

[profile.default]
status-level = "pass"
final-status-level = "pass"
success-output = "immediate"
slow-timeout = { period = "10s", terminate-after = 1, grace-period = "2s" }

[profile.ci]
fail-fast = false
slow-timeout = { period = "10s", terminate-after = 1, grace-period = "2s" }

[profile.ci.junit]
path = "target/nextest/ci/junit.xml"

[store]
dir = "target/nextest"
