nextest-version = "0.9.95"

[profile.default]
status-level = "pass"
final-status-level = "pass"
success-output = "immediate"

[profile.ci]
fail-fast = false
slow-timeout = { period = "90s", terminate-after = 3, grace-period = "30s" }

[profile.ci.junit]
path = "junit.xml"

[store]
dir = "target/nextest"
